package com.gmkornilov.shikimori.domain.models

import java.util.*

data class AnimeInfo(
    val id: Long,
    val name: String,
    val russianName: String,
    val imageInfo: ImageInfo,
    val url: String,
    val kind: AnimeKind,
    val score: Float,
    val status: AnimeStatus,
    val episodes: Int,
    val episodesAired: Int,
    val airedOn: Date?,
    val releasedOn: Date?,
    val rating: String,
    val english: List<String?>,
    val japanese: List<String?>,
    val synonyms: List<String?>,
    val ruLicenseName: String?,
    val duration: Int,
    val description: String?,
    val descriptionHtml: String,
    val descriptionSource: String?,
    val franchise: String?,
    val favoured: Boolean,
    val anons: Boolean,
    val ongoing: Boolean,
    val threadId: Long,
    val topicId: Long,
    val myAnimeListId: Long,
    val ratesScoresStats: List<NamedStat>,
    val ratesStatusesStats: List<NamedStat>,
    val updatedAt: Date,
    val nextEpisodeAt: Date?,
    val fansubbers: List<String>?,
    val fandubbers: List<String>?,
    val genres: List<Genre>,
    val studios: List<Studio>,
    val videos: List<String>,
    val screenshots: List<Screenshot>,
    val userRate: Float,
)
