package com.gmkornilov.shikimori.domain.models.common

import java.util.*


data class AnimeInfo(
    val id: Long,
    val name: String,
    val russianName: String,
    val imageInfo: ImageInfo,
    val url: String? = null,
    val kind: AnimeKind? = null,
    val score: Float? = null,
    val status: AnimeStatus? = null,
    val episodes: Int? = null,
    val episodesAired: Int? = null,
    val airedOn: Date? = null,
    val releasedOn: Date? = null,
    val rating: AnimeRating? = null,
    val english: List<String?>? = null,
    val japanese: List<String?>? = null,
    val synonyms: List<String?>? = null,
    val ruLicenseName: String? = null,
    val duration: Int? = null,
    val description: String? = null,
    val descriptionHtml: String? = null,
    val descriptionSource: String? = null,
    val franchise: String? = null,
    val favoured: Boolean? = null,
    val anons: Boolean? = null,
    val ongoing: Boolean? = null,
    val threadId: Long? = null,
    val topicId: Long? = null,
    val myAnimeListId: Long? = null,
    val ratesScoresStats: List<NamedStat>? = null,
    val ratesStatusesStats: List<NamedStat>? = null,
    val updatedAt: Date? = null,
    val nextEpisodeAt: Date? = null,
    val fansubbers: List<String>? = null,
    val fandubbers: List<String>? = null,
    val genres: List<Genre>? = null,
    val studios: List<Studio>? = null,
    val videos: List<String>? = null,
    val screenshots: List<Screenshot>? = null,
    val userRate: Float? = null,
)
